#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert FeaturedScreen function before AegisShowcaseScreen"""

with open('src/App.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

assert content.count('function AegisShowcaseScreen({setScreen}){') == 1, "AegisShowcaseScreen not found"

FEATURED_CODE = (
    "// \u2500\u2500\u2500 FEATURED EVENTS SCREEN \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n\n"
    'var FEATURED_EVENTS=[\n'
    '  {id:"clash-kings-3",name:"Clash Kings Invitational #3",host:"ClashKings",sponsor:"RiotBar",status:"live",date:"Mar 17 2026",time:"NOW",format:"Double Elim",size:16,registered:16,prizePool:"$100",region:"EUW",description:"Invite-only invitational for top EUW players. Live brackets and real-time commentary.",tags:["Invite Only","EUW","Broadcast"],logo:"\U0001F451",screen:null},\n'
    '  {id:"aegis-152",name:"Aegis Esports TFT Showdown #152",host:"Aegis Esports",sponsor:"ZenMarket",status:"upcoming",date:"Mar 22 2026",time:"8:00 PM EST",format:"Swiss (6 rounds)",size:64,registered:47,prizePool:"$200",region:"NA/LATAM",description:"The premier weekly TFT series. Open to all ranked players. Top 8 earn prizes and broadcast coverage.",tags:["Broadcast","Prizes","Open"],logo:"\U0001F3C6",screen:"aegis-showcase"},\n'
    '  {id:"tft-academy-8",name:"TFT Academy Weekly #8",host:"TFT Academy",sponsor:null,status:"upcoming",date:"Mar 21 2026",time:"6:00 PM CET",format:"Single Lobby",size:8,registered:6,prizePool:null,region:"EMEA",description:"Community learning series for Diamond+ players. Coaches analyze every game post-tournament.",tags:["Educational","EMEA","Diamond+"],logo:"\U0001F393",screen:null},\n'
    '  {id:"aegis-151",name:"Aegis Esports TFT Showdown #151",host:"Aegis Esports",sponsor:"ZenMarket",status:"completed",date:"Mar 15 2026",format:"Swiss",size:64,registered:64,prizePool:"$200",region:"NA/LATAM",champion:"D0PA#111",top4:["D0PA#111","LC Abyss#CAPO","vnck#NA1","Ken Kitade"],logo:"\U0001F3C6",screen:"aegis-showcase"},\n'
    '  {id:"tft-community-feb",name:"TFT Community Open \u2014 February",host:"TFT Community",sponsor:null,status:"completed",date:"Feb 28 2026",format:"Swiss",size:32,registered:32,prizePool:null,champion:"Levitate",top4:["Levitate","Zounderkite","Uri","BingBing"],logo:"\u26A1",screen:null},\n'
    '  {id:"clash-kings-2",name:"Clash Kings Invitational #2",host:"ClashKings",sponsor:"RiotBar",status:"completed",date:"Feb 14 2026",format:"Double Elim",size:16,registered:16,prizePool:"$100",region:"EUW",champion:"StarForge",top4:["StarForge","IronMask","DawnBreaker","GhostRider"],logo:"\U0001F451",screen:null},\n'
    '];\n\n'
    'function FeaturedScreen({setScreen,currentUser,onAuthClick,toast}){\n'
    '  var [filter,setFilter]=useState("all");\n'
    '  var live=FEATURED_EVENTS.filter(function(e){return e.status==="live";});\n'
    '  var upcoming=FEATURED_EVENTS.filter(function(e){return e.status==="upcoming";});\n'
    '  var past=FEATURED_EVENTS.filter(function(e){return e.status==="completed";});\n'
    '  var active=live.concat(upcoming);\n'
    '  var shown=filter==="all"?active:filter==="live"?live:upcoming;\n\n'
    '  return(\n'
    '    <div className="page wrap">\n\n'
    '      <div style={{marginBottom:28}}>\n'
    '        <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:6,flexWrap:"wrap"}}>\n'
    '          <h1 style={{color:"#F2EDE4",fontSize:24,fontWeight:700,margin:0}}>Featured Events</h1>\n'
    '          {live.length>0&&(\n'
    '            <span style={{display:"flex",alignItems:"center",gap:5,background:"rgba(82,196,124,.12)",border:"1px solid rgba(82,196,124,.3)",borderRadius:20,padding:"4px 10px",fontSize:11,fontWeight:700,color:"#6EE7B7"}}>\n'
    '              <span style={{width:6,height:6,borderRadius:"50%",background:"#52C47C",animation:"pulse 1.5s infinite",display:"inline-block"}}/>\n'
    '              {live.length} LIVE NOW\n'
    '            </span>\n'
    '          )}\n'
    '        </div>\n'
    '        <p style={{color:"#BECBD9",fontSize:13,margin:0}}>Partner tournaments, community clashes and special events. Free to watch, free to enter.</p>\n'
    '      </div>\n\n'
    '      <div style={{display:"flex",gap:6,marginBottom:20}}>\n'
    '        {[["all","All Active"],["live","Live Now"],["upcoming","Upcoming"]].map(function(arr){\n'
    '          var f=arr[0],label=arr[1];\n'
    '          return(\n'
    '            <button key={f} onClick={function(){setFilter(f)}}\n'
    '              style={{background:filter===f?"rgba(155,114,207,.2)":"rgba(255,255,255,.04)",border:"1px solid "+(filter===f?"rgba(155,114,207,.5)":"rgba(242,237,228,.08)"),borderRadius:20,padding:"5px 14px",fontSize:12,fontWeight:600,color:filter===f?"#C4B5FD":"#BECBD9",cursor:"pointer",fontFamily:"inherit",transition:"all .15s"}}>\n'
    '              {label}\n'
    '            </button>\n'
    '          );\n'
    '        })}\n'
    '      </div>\n\n'
    '      {live.length>0&&(function(){\n'
    '        var hero=live[0];\n'
    '        return(\n'
    '          <div style={{background:"linear-gradient(145deg,#0D1520,#0f1827)",border:"1px solid rgba(232,168,56,.3)",borderRadius:16,overflow:"hidden",marginBottom:20,cursor:hero.screen?"pointer":"default"}}\n'
    '            onClick={function(){if(hero.screen){setScreen(hero.screen);}}}>\n'
    '            <div style={{background:"rgba(232,168,56,.07)",borderBottom:"1px solid rgba(232,168,56,.18)",padding:"9px 18px",display:"flex",alignItems:"center",gap:8}}>\n'
    '              <span style={{display:"flex",alignItems:"center",gap:5,background:"rgba(82,196,124,.15)",border:"1px solid rgba(82,196,124,.35)",borderRadius:20,padding:"3px 10px",fontSize:11,fontWeight:700,color:"#6EE7B7"}}>\n'
    '                <span style={{width:5,height:5,borderRadius:"50%",background:"#52C47C",animation:"pulse 1.5s infinite",display:"inline-block"}}/>LIVE NOW\n'
    '              </span>\n'
    '              <span style={{color:"#E8A838",fontWeight:600,fontSize:12,marginLeft:4}}>Round in progress</span>\n'
    '            </div>\n'
    '            <div style={{padding:"20px 22px"}}>\n'
    '              <div style={{display:"flex",gap:14,alignItems:"flex-start",flexWrap:"wrap"}}>\n'
    '                <div style={{width:52,height:52,borderRadius:14,background:"rgba(155,114,207,.12)",border:"1px solid rgba(155,114,207,.3)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,flexShrink:0}}>{hero.logo}</div>\n'
    '                <div style={{flex:1,minWidth:0}}>\n'
    '                  <div style={{fontWeight:700,fontSize:18,color:"#F2EDE4",marginBottom:4}}>{hero.name}</div>\n'
    '                  <div style={{fontSize:12,color:"#9B72CF",fontWeight:600,marginBottom:10}}>Hosted by {hero.host}{hero.sponsor?" \xb7 Presented by "+hero.sponsor:""}</div>\n'
    '                  <div style={{fontSize:13,color:"#C8D4E0",lineHeight:1.5,marginBottom:14}}>{hero.description}</div>\n'
    '                  <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>\n'
    '                    {(hero.tags||[]).map(function(t){return(\n'
    '                      <span key={t} style={{background:"rgba(155,114,207,.1)",border:"1px solid rgba(155,114,207,.25)",borderRadius:20,padding:"3px 9px",fontSize:10,fontWeight:700,color:"#C4B5FD"}}>{t}</span>\n'
    '                    );})\n'
    '                    }\n'
    '                    <span style={{background:"rgba(232,168,56,.08)",border:"1px solid rgba(232,168,56,.2)",borderRadius:20,padding:"3px 9px",fontSize:10,fontWeight:700,color:"#E8A838"}}>{hero.registered}/{hero.size} players</span>\n'
    '                    {hero.prizePool&&<span style={{background:"rgba(78,205,196,.08)",border:"1px solid rgba(78,205,196,.2)",borderRadius:20,padding:"3px 9px",fontSize:10,fontWeight:700,color:"#4ECDC4"}}>{hero.prizePool}</span>}\n'
    '                  </div>\n'
    '                </div>\n'
    '              </div>\n'
    '            </div>\n'
    '          </div>\n'
    '        );\n'
    '      })()}\n\n'
    '      {shown.length>0&&(\n'
    '        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14,marginBottom:32}}>\n'
    '          {shown.map(function(ev){\n'
    '            var isLive=ev.status==="live";\n'
    '            return(\n'
    '              <div key={ev.id}\n'
    '                style={{background:"linear-gradient(145deg,#0D1520,#0f1827)",border:"1px solid rgba(155,114,207,.2)",borderRadius:14,overflow:"hidden",cursor:ev.screen?"pointer":"default",transition:"border-color .2s"}}\n'
    '                onMouseEnter={function(e){e.currentTarget.style.borderColor="rgba(155,114,207,.5)";}}\n'
    '                onMouseLeave={function(e){e.currentTarget.style.borderColor="rgba(155,114,207,.2)";}}\n'
    '                onClick={function(){if(ev.screen){setScreen(ev.screen);}}}>\n'
    '                <div style={{padding:"16px 18px"}}>\n'
    '                  <div style={{display:"flex",alignItems:"flex-start",gap:10,marginBottom:10}}>\n'
    '                    <div style={{width:38,height:38,borderRadius:10,background:"rgba(155,114,207,.1)",border:"1px solid rgba(155,114,207,.2)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0}}>{ev.logo}</div>\n'
    '                    <div style={{flex:1,minWidth:0}}>\n'
    '                      <div style={{fontWeight:700,fontSize:13,color:"#F2EDE4",lineHeight:1.3,marginBottom:2}}>{ev.name}</div>\n'
    '                      <div style={{fontSize:11,color:"#9B72CF",fontWeight:600}}>{ev.host}</div>\n'
    '                    </div>\n'
    '                    <div style={{flexShrink:0}}>\n'
    '                      {isLive?(\n'
    '                        <span style={{display:"flex",alignItems:"center",gap:4,background:"rgba(82,196,124,.12)",border:"1px solid rgba(82,196,124,.3)",borderRadius:20,padding:"3px 8px",fontSize:9,fontWeight:700,color:"#6EE7B7"}}>\n'
    '                          <span style={{width:4,height:4,borderRadius:"50%",background:"#52C47C",animation:"pulse 1.5s infinite",display:"inline-block"}}/>LIVE\n'
    '                        </span>\n'
    '                      ):(\n'
    '                        <span style={{background:"rgba(78,205,196,.08)",border:"1px solid rgba(78,205,196,.2)",borderRadius:20,padding:"3px 8px",fontSize:9,fontWeight:700,color:"#4ECDC4"}}>UPCOMING</span>\n'
    '                      )}\n'
    '                    </div>\n'
    '                  </div>\n'
    '                  <div style={{fontSize:12,color:"#C8D4E0",lineHeight:1.5,marginBottom:12}}>{ev.description}</div>\n'
    '                  <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:12}}>\n'
    '                    <span style={{background:"rgba(255,255,255,.04)",borderRadius:6,padding:"3px 8px",fontSize:10,color:"#BECBD9"}}>{ev.date}</span>\n'
    '                    {ev.time&&<span style={{background:"rgba(255,255,255,.04)",borderRadius:6,padding:"3px 8px",fontSize:10,color:"#BECBD9"}}>{ev.time}</span>}\n'
    '                    {ev.region&&<span style={{background:"rgba(255,255,255,.04)",borderRadius:6,padding:"3px 8px",fontSize:10,color:"#BECBD9"}}>{ev.region}</span>}\n'
    '                  </div>\n'
    '                  <div style={{marginBottom:10}}>\n'
    '                    <div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}>\n'
    '                      <span style={{fontSize:10,color:"#BECBD9"}}>Registration</span>\n'
    '                      <span style={{fontSize:10,fontWeight:700,color:"#E8A838"}}>{ev.registered}/{ev.size}</span>\n'
    '                    </div>\n'
    '                    <Bar val={ev.registered} max={ev.size} color="#E8A838" h={4}/>\n'
    '                  </div>\n'
    '                  <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>\n'
    '                    {ev.prizePool&&<span style={{background:"rgba(78,205,196,.08)",border:"1px solid rgba(78,205,196,.2)",borderRadius:20,padding:"3px 8px",fontSize:10,fontWeight:700,color:"#4ECDC4"}}>{ev.prizePool}</span>}\n'
    '                    {ev.sponsor&&<span style={{background:"rgba(155,114,207,.08)",border:"1px solid rgba(155,114,207,.2)",borderRadius:20,padding:"3px 8px",fontSize:10,fontWeight:600,color:"#C4B5FD"}}>by {ev.sponsor}</span>}\n'
    '                    {ev.screen&&(\n'
    '                      <button style={{marginLeft:"auto",background:"rgba(155,114,207,.12)",border:"1px solid rgba(155,114,207,.3)",borderRadius:7,padding:"5px 12px",fontSize:11,fontWeight:700,color:"#C4B5FD",cursor:"pointer",fontFamily:"inherit"}}\n'
    '                        onClick={function(e){e.stopPropagation();setScreen(ev.screen);}}>View\n'
    '                      </button>\n'
    '                    )}\n'
    '                  </div>\n'
    '                </div>\n'
    '              </div>\n'
    '            );\n'
    '          })}\n'
    '        </div>\n'
    '      )}\n\n'
    '      {shown.length===0&&(\n'
    '        <div style={{textAlign:"center",padding:"48px 24px",color:"#BECBD9",marginBottom:24}}>\n'
    '          <div style={{fontSize:32,marginBottom:12}}>\U0001F4C5</div>\n'
    '          <div style={{fontSize:14}}>No events matching this filter right now.</div>\n'
    '        </div>\n'
    '      )}\n\n'
    '      {past.length>0&&(\n'
    '        <div style={{marginBottom:32}}>\n'
    '          <h3 style={{color:"#F2EDE4",fontSize:15,fontWeight:700,marginBottom:14}}>Past Events</h3>\n'
    '          <div style={{display:"flex",flexDirection:"column",gap:8}}>\n'
    '            {past.map(function(ev){\n'
    '              return(\n'
    '                <div key={ev.id}\n'
    '                  style={{background:"#111827",border:"1px solid rgba(242,237,228,.06)",borderRadius:12,padding:"14px 18px",display:"flex",alignItems:"center",gap:14,cursor:ev.screen?"pointer":"default",transition:"border-color .2s"}}\n'
    '                  onMouseEnter={function(e){if(ev.screen)e.currentTarget.style.borderColor="rgba(155,114,207,.3)";}}\n'
    '                  onMouseLeave={function(e){e.currentTarget.style.borderColor="rgba(242,237,228,.06)";}}\n'
    '                  onClick={function(){if(ev.screen){setScreen(ev.screen);}}}>\n'
    '                  <div style={{fontSize:20,flexShrink:0}}>{ev.logo}</div>\n'
    '                  <div style={{flex:1,minWidth:0}}>\n'
    '                    <div style={{fontWeight:600,fontSize:13,color:"#F2EDE4",marginBottom:2}}>{ev.name}</div>\n'
    '                    <div style={{fontSize:11,color:"#BECBD9"}}>{ev.date} \xb7 {ev.registered} players \xb7 {ev.format}</div>\n'
    '                  </div>\n'
    '                  {ev.champion&&(\n'
    '                    <div style={{textAlign:"right",flexShrink:0}}>\n'
    '                      <div style={{fontSize:10,color:"#BECBD9",marginBottom:2}}>Champion</div>\n'
    '                      <div style={{fontSize:12,fontWeight:700,color:"#E8A838"}}>\U0001F3C6 {ev.champion}</div>\n'
    '                    </div>\n'
    '                  )}\n'
    '                  {ev.screen&&<span style={{fontSize:12,color:"#9B72CF",flexShrink:0}}>\u2192</span>}\n'
    '                </div>\n'
    '              );\n'
    '            })}\n'
    '          </div>\n'
    '        </div>\n'
    '      )}\n\n'
    '      <div style={{background:"linear-gradient(135deg,rgba(155,114,207,.08),rgba(78,205,196,.05))",border:"1px solid rgba(155,114,207,.2)",borderRadius:16,padding:"28px 24px",textAlign:"center"}}>\n'
    '        <div style={{fontSize:28,marginBottom:10}}>\U0001F3AE</div>\n'
    '        <h3 style={{color:"#F2EDE4",fontSize:18,fontWeight:700,marginBottom:8}}>Run Your Own Tournament</h3>\n'
    '        <p style={{fontSize:13,color:"#BECBD9",lineHeight:1.7,marginBottom:20,maxWidth:420,margin:"0 auto 20px"}}>\n'
    '          Get featured here. Create and manage TFT tournaments with our full host suite.\n'
    '        </p>\n'
    '        <div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}>\n'
    '          <Btn v="primary" onClick={function(){currentUser?setScreen("host-apply"):onAuthClick("signup");}}>Apply to Host</Btn>\n'
    '          <Btn v="dark" onClick={function(){setScreen("pricing");}}>View Host Plans</Btn>\n'
    '        </div>\n'
    '      </div>\n\n'
    '    </div>\n'
    '  );\n'
    '}\n\n'
)

old7 = 'function AegisShowcaseScreen({setScreen}){'
content = content.replace(old7, FEATURED_CODE + old7, 1)

opens = content.count('{')
closes = content.count('}')
balance = opens - closes
print(f"Brace balance: {opens} - {closes} = {balance}")

if balance != 0:
    print("ERROR: brace balance is not 0!")
    exit(1)

with open('src/App.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

# Verify FeaturedScreen is present
assert 'function FeaturedScreen' in content, "FeaturedScreen not in output!"
assert 'var FEATURED_EVENTS=' in content, "FEATURED_EVENTS not in output!"
print("Verification passed!")
print("Done. Lines:", content.count('\n'))
