import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffddaf",
        "on-tertiary-fixed": "#00201e",
        "on-primary": "#432c00",
        "tertiary-container": "#45c6bd",
        "surface-tint": "#fdba49",
        "tertiary-fixed": "#7cf6ec",
        "primary": "#ffc66b",
        "inverse-on-surface": "#303038",
        "secondary-container": "#5c348d",
        "on-surface": "#e4e1ec",
        "on-tertiary-container": "#004f4a",
        "on-error": "#690005",
        "on-tertiary": "#003734",
        "error-container": "#93000a",
        "primary-container": "#e8a838",
        "on-secondary": "#421773",
        "secondary-fixed": "#eedcff",
        "on-secondary-fixed-variant": "#59328b",
        "on-background": "#e4e1ec",
        "outline-variant": "#504535",
        "surface-container-lowest": "#0e0d15",
        "surface-container": "#1f1f27",
        "on-secondary-fixed": "#2a0054",
        "surface-container-highest": "#34343c",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#5dd9d0",
        "surface-container-low": "#1b1b23",
        "surface": "#13131a",
        "secondary-fixed-dim": "#d9b9ff",
        "on-primary-fixed-variant": "#614000",
        "secondary": "#d9b9ff",
        "on-primary-fixed": "#281800",
        "inverse-surface": "#e4e1ec",
        "inverse-primary": "#805600",
        "tertiary": "#67e2d9",
        "on-primary-container": "#5f3f00",
        "outline": "#9d8e7c",
        "background": "#13131a",
        "on-tertiary-fixed-variant": "#00504c",
        "surface-dim": "#13131a",
        "on-surface-variant": "#d5c4af",
        "surface-variant": "#34343c",
        "surface-container-high": "#2a2931",
        "surface-bright": "#393841",
        "primary-fixed-dim": "#fdba49",
        "on-secondary-container": "#cea7ff",
        "success": "#6ee7b7",
        "warning": "#fb923c",
        "medal-gold": "#e8a838",
        "medal-silver": "#c0c0c0",
        "medal-bronze": "#cd7f32",
        "muted": "#9aabbf",
      },
      fontFamily: {
        // Primary tokens
        "display":    ["Russo One", "sans-serif"],
        "headline":   ["Space Grotesk", "sans-serif"],
        "editorial":  ["Playfair Display", "serif"],
        "serif":      ["Playfair Display", "serif"],
        "body":       ["Inter", "sans-serif"],
        "label":      ["Barlow Condensed", "sans-serif"],
        "mono":       ["JetBrains Mono", "monospace"],
        // Aliases (all Barlow Condensed)
        "sans":           ["Barlow Condensed", "sans-serif"],
        "condensed":      ["Barlow Condensed", "sans-serif"],
        "sans-condensed": ["Barlow Condensed", "sans-serif"],
        "sans-cond":      ["Barlow Condensed", "sans-serif"],
        "nav":            ["Barlow Condensed", "sans-serif"],
        "technical":      ["Barlow Condensed", "sans-serif"],
        "stats":          ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms, containerQueries],
}
